language: c

os:
  - linux

before_install:
  - wget -c https://releases.linaro.org/components/toolchain/binaries/7.2-2017.11/aarch64-linux-gnu/gcc-linaro-7.2.1-2017.11-x86_64_aarch64-linux-gnu.tar.xz
  - tar xf gcc-linaro-7.2.1-2017.11-x86_64_aarch64-linux-gnu.tar.xz
  - export PATH=$PATH:$PWD/gcc-linaro-7.2.1-2017.11-x86_64_aarch64-linux-gnu/bin/
  - aarch64-linux-gnu-gcc --version
  - sudo apt-get install bc git

script:
  - git clone https://github.com/mbgg/linux-mediatek.git linux-mediatek
  - cd linux-mediatek
  - git checkout for-next
  - export ARCH=arm64
  - export CROSS_COMPILE=aarch64-linux-gnu-
  - make defconfig
  - make -j$(nproc --all) all
