language: c

os:
  - linux

before_install:
  sudo apt-get install bc git mpc

before_script:
  - if [[ "${ARCH}" == "arm64" ]]; then
      wget -c https://releases.linaro.org/components/toolchain/binaries/7.2-2017.11/aarch64-linux-gnu/gcc-linaro-7.2.1-2017.11-x86_64_aarch64-linux-gnu.tar.xz &&
      tar xf gcc-linaro-7.2.1-2017.11-x86_64_aarch64-linux-gnu.tar.xz &&
      export PATH=$PATH:$PWD/gcc-linaro-7.2.1-2017.11-x86_64_aarch64-linux-gnu/bin/ &&
      aarch64-linux-gnu-gcc --version &&
      export ARCH=arm64 &&
      export CROSS_COMPILE=aarch64-linux-gnu- ;
    fi

  - if [[ "${ARCH}" == "arm" ]]; then
      wget -c https://releases.linaro.org/components/toolchain/binaries/7.5-2019.12/arm-linux-gnueabihf/gcc-linaro-7.5.0-2019.12-i686_arm-linux-gnueabihf.tar.xz &&
      tar xf gcc-linaro-7.5.0-2019.12-i686_arm-linux-gnueabihf.tar.xz &&
      export PATH=$PATH:$PWD/gcc-linaro-7.5.0-2019.12-i686_arm-linux-gnueabihf/bin/ &&
      arm-linux-gnueabihf-gcc --version &&
      export ARCH=arm &&
      export CROSS_COMPILE=arm-linux-gnueabihf- ;
    fi

script:
  - git clone https://git.kernel.org/pub/scm/linux/kernel/git/matthias.bgg/linux.git
  - cd linux
  - git checkout for-next
  - make ${CONFIG}
  - make -j$(nproc --all) ${TARGET}

matrix:
  include:

    # ARM64
    - name: "arm64 soc drivers"
      env:
        - ARCH="arm64"
          CONFIG="allmodconfig"
          TARGET="drivers/soc/mediatek/"

    - name: "arm64 soc dtbs"
      env:
        - ARCH="arm64"
          CONFIG="defconfig"
          TARGET="mediatek/*.dtb"

    - name: "arm64 all modules"
      env:
        - ARCH="arm64"
          CONFIG="defconfig"
          TARGET="modules"

    - name: "arm64 Image"
      env:
        - ARCH="arm64"
          CONFIG="defconfig"
          TARGET="Image"

    # ARM32
    - name: "arm32 soc drivers"
      env:
        - ARCH="arm"
          CONFIG="allmodconfig"
          TARGET="drivers/soc/mediatek/"

    - name: "arm32 soc dtbs"
      env:
        - ARCH="arm"
          CONFIG="defconfig"
          TARGET="mt*.dtb"

    - name: "arm32 all modules"
      env:
        - ARCH="arm"
          CONFIG="defconfig"
          TARGET="modules"

    - name: "arm32 zImage"
      env:
        - ARCH="arm"
          CONFIG="defconfig"
          TARGET="zImage"

